//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xaml.Tests.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dummy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dummy() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xaml.Tests.Resources.Dummy", typeof(Dummy).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot; Container.Property=&quot;Value&quot;&gt;&lt;/DummyClass&gt;.
        /// </summary>
        public static string AttachedProperty {
            get {
                return ResourceManager.GetString("AttachedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;Bad&lt;/&gt;.
        /// </summary>
        public static string BadFormat {
            get {
                return ResourceManager.GetString("BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;&gt;
        ///  &lt;DummyClass.Items&gt;
        ///    &lt;Item /&gt;
        ///    &lt;Item /&gt;
        ///    &lt;Item /&gt;
        ///  &lt;/DummyClass.Items&gt;
        ///&lt;/DummyClass&gt;.
        /// </summary>
        public static string ChildCollection {
            get {
                return ResourceManager.GetString("ChildCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;&gt;
        ///  &lt;DummyClass.Items&gt;
        ///    &lt;Item/&gt;
        ///  &lt;/DummyClass.Items&gt;
        ///&lt;/DummyClass&gt;.
        /// </summary>
        public static string ClassWithInnerCollection {
            get {
                return ResourceManager.GetString("ClassWithInnerCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot; /&gt;.
        /// </summary>
        public static string CollapsedTag {
            get {
                return ResourceManager.GetString("CollapsedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot; SampleProperty=&quot;SomeText&quot; /&gt;.
        /// </summary>
        public static string CollapsedTagWithProperty {
            get {
                return ResourceManager.GetString("CollapsedTagWithProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;&gt;
        ///  &lt;Item Title=&quot;Main1&quot; /&gt;
        ///  &lt;Item Title=&quot;Main2&quot; /&gt;
        ///  &lt;DummyClass.Child&gt;
        ///    &lt;ChildClass&gt;
        ///      &lt;Item&gt;
        ///        &lt;Item Title=&quot;Item1&quot; /&gt;
        ///        &lt;Item Title=&quot;Item2&quot; /&gt;
        ///        &lt;Item Title=&quot;Item3&quot; /&gt;
        ///      &lt;/Item&gt;
        ///      &lt;ChildClass.Child&gt;
        ///        &lt;ChildClass /&gt;
        ///      &lt;/ChildClass.Child&gt;
        ///    &lt;/ChildClass&gt;
        ///  &lt;/DummyClass.Child&gt;
        ///&lt;/DummyClass&gt;.
        /// </summary>
        public static string CollectionsContentPropertyNesting {
            get {
                return ResourceManager.GetString("CollectionsContentPropertyNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;&gt;
        ///  &lt;DummyClass.Items&gt;
        ///    &lt;Item Title=&quot;SomeTitle&quot; /&gt;
        ///  &lt;/DummyClass.Items&gt;
        ///&lt;/DummyClass&gt;.
        /// </summary>
        public static string CollectionWithClosedItemAndProperty {
            get {
                return ResourceManager.GetString("CollectionWithClosedItemAndProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;Grid xmlns=&quot;root&quot;&gt;
        ///  &lt;Grid.Children&gt;
        ///    &lt;TextBlock&gt;
        ///    &lt;/TextBlock&gt;
        ///    &lt;TextBlock /&gt;
        ///  &lt;/Grid.Children&gt;
        ///&lt;/Grid&gt;.
        /// </summary>
        public static string CollectionWithMixedEmptyAndNotEmptyNestedElements {
            get {
                return ResourceManager.GetString("CollectionWithMixedEmptyAndNotEmptyNestedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;&gt;
        ///  &lt;DummyClass.Items&gt;
        ///    &lt;Item/&gt;
        ///    &lt;Item/&gt;
        ///    &lt;Item/&gt;
        ///  &lt;/DummyClass.Items&gt;
        ///&lt;/DummyClass&gt;.
        /// </summary>
        public static string CollectionWithMoreThanOneItem {
            get {
                return ResourceManager.GetString("CollectionWithMoreThanOneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;&gt;
        ///  &lt;Item /&gt;
        ///  &lt;Item /&gt;
        ///&lt;/DummyClass&gt;.
        /// </summary>
        public static string ContentPropertyForCollectionMoreThanOneElement {
            get {
                return ResourceManager.GetString("ContentPropertyForCollectionMoreThanOneElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;&gt;
        ///  &lt;Item /&gt;
        ///&lt;/DummyClass&gt;.
        /// </summary>
        public static string ContentPropertyForCollectionOneElement {
            get {
                return ResourceManager.GetString("ContentPropertyForCollectionOneElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;ChildClass xmlns=&quot;root&quot;&gt;
        ///  &lt;Item /&gt;
        ///&lt;/ChildClass&gt;.
        /// </summary>
        public static string ContentPropertyForSingleMember {
            get {
                return ResourceManager.GetString("ContentPropertyForSingleMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;
        ///            xmlns:x=&quot;another&quot; &gt;
        ///  &lt;DummyClass.ChildFromAnotherNamespace&gt;
        ///    &lt;x:Foreigner /&gt;
        ///  &lt;/DummyClass.ChildFromAnotherNamespace&gt;
        ///&lt;/DummyClass&gt;.
        /// </summary>
        public static string DifferentNamespaces {
            get {
                return ResourceManager.GetString("DifferentNamespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;
        ///            xmlns:x=&quot;another&quot; SampleProperty=&quot;One&quot; AnotherProperty=&quot;Two&quot;&gt;
        ///  &lt;DummyClass.ChildFromAnotherNamespace&gt;
        ///    &lt;x:Foreigner /&gt;
        ///  &lt;/DummyClass.ChildFromAnotherNamespace&gt;
        ///&lt;/DummyClass&gt;.
        /// </summary>
        public static string DifferentNamespacesAndMoreThanOneProperty {
            get {
                return ResourceManager.GetString("DifferentNamespacesAndMoreThanOneProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot; EnumProperty=&quot;One&quot;&gt;&lt;/DummyClass&gt;.
        /// </summary>
        public static string EnumProperty {
            get {
                return ResourceManager.GetString("EnumProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NamespaceDeclarationNamespaceDeclarationNamespaceDeclarationNamespaceDeclarationNamespaceDeclarationStartObjectStartMemberValueEndMemberStartMemberValueEndMemberStartMemberValueEndMemberStartMemberValueEndMemberStartMemberStartObjectStartMemberValueEndMemberStartMemberStartObjectStartMemberValueEndMemberEndObjectValueStartObjectStartMemberValueEndMemberEndObjectValueStartObjectStartMemberValueEndMemberEndObjectEndMemberStartMemberStartObjectStartMemberValueEndMemberStartMemberValueEndMemberStartMemberValueE [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string ExpectedStage1 {
            get {
                return ResourceManager.GetString("ExpectedStage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;&gt;
        ///  &lt;DummyClass.Child&gt;
        ///    &lt;ChildClass&gt;&lt;/ChildClass&gt;
        ///  &lt;/DummyClass.Child&gt;
        ///&lt;/DummyClass&gt;.
        /// </summary>
        public static string ExpectedStage11 {
            get {
                return ResourceManager.GetString("ExpectedStage11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;&gt;
        ///  &lt;DummyClass.Child&gt;
        ///    &lt;ChildClass&gt;
        ///      &lt;ChildClass.Child&gt;
        ///        &lt;ChildClass&gt;
        ///          &lt;ChildClass.Child&gt;
        ///            &lt;ChildClass/&gt;
        ///          &lt;/ChildClass.Child&gt;
        ///        &lt;/ChildClass&gt;
        ///      &lt;/ChildClass.Child&gt;
        ///    &lt;/ChildClass&gt;
        ///  &lt;/DummyClass.Child&gt;
        ///&lt;/DummyClass&gt;.
        /// </summary>
        public static string FourLevelsOfNesting {
            get {
                return ResourceManager.GetString("FourLevelsOfNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;&gt;
        ///  &lt;DummyClass.Child&gt;
        ///    &lt;ChildClass&gt;&lt;/ChildClass&gt;
        ///  &lt;/DummyClass.Child&gt;
        ///&lt;/DummyClass&gt;.
        /// </summary>
        public static string InstanceWithChild {
            get {
                return ResourceManager.GetString("InstanceWithChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;ChildClass xmlns=&quot;root&quot;&gt;
        ///  &lt;Item /&gt;
        ///&lt;/ChildClass&gt;.
        /// </summary>
        public static string InstanceWithCollapsedChildThatUsesContentProperty {
            get {
                return ResourceManager.GetString("InstanceWithCollapsedChildThatUsesContentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot; SampleProperty=&quot;{Parameterized Parameter}&quot;/&gt;.
        /// </summary>
        public static string MarkupExtensionCtorWith1StringArgument {
            get {
                return ResourceManager.GetString("MarkupExtensionCtorWith1StringArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;
        ///            SampleProperty=&quot;{Dummy Property=&apos;Some Value&apos;}&quot;
        ///            AnotherProperty=&quot;{Dummy Property=&apos;Another Value&apos;}&quot; /&gt;.
        /// </summary>
        public static string MarkupExtensionTwoQuotedValues {
            get {
                return ResourceManager.GetString("MarkupExtensionTwoQuotedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot; SampleProperty=&quot;{Dummy Option}&quot;/&gt;.
        /// </summary>
        public static string MarkupExtensionWithOption {
            get {
                return ResourceManager.GetString("MarkupExtensionWithOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;&gt;
        ///  &lt;ChildClass /&gt;
        ///&lt;/DummyClass&gt;.
        /// </summary>
        public static string NestedChildWithoutPropertyName {
            get {
                return ResourceManager.GetString("NestedChildWithoutPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;x:DummyClass xmlns:x=&quot;nonRoot&quot;&gt;&lt;/x:DummyClass&gt;.
        /// </summary>
        public static string NonRootNamespace {
            get {
                return ResourceManager.GetString("NonRootNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot; Number=&quot;1234&quot;&gt;&lt;/DummyClass&gt;.
        /// </summary>
        public static string NonStringProperty {
            get {
                return ResourceManager.GetString("NonStringProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;&gt;&lt;/DummyClass&gt;.
        /// </summary>
        public static string RootNamespace {
            get {
                return ResourceManager.GetString("RootNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot; SampleProperty=&quot;{Dummy}&quot;/&gt;.
        /// </summary>
        public static string SimpleExtension {
            get {
                return ResourceManager.GetString("SimpleExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot; SampleProperty=&quot;{Dummy Property=SomeValue}&quot;/&gt;.
        /// </summary>
        public static string SimpleExtensionWithOneAssignment {
            get {
                return ResourceManager.GetString("SimpleExtensionWithOneAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;&gt;&lt;/DummyClass&gt;.
        /// </summary>
        public static string SingleInstance {
            get {
                return ResourceManager.GetString("SingleInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot; SampleProperty=&quot;Property!&quot;&gt;&lt;/DummyClass&gt;.
        /// </summary>
        public static string StringProperty {
            get {
                return ResourceManager.GetString("StringProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;&gt;
        ///  &lt;DummyClass.Child&gt;
        ///    &lt;ChildClass&gt;
        ///      &lt;ChildClass.Child&gt;
        ///        &lt;ChildClass/&gt;
        ///      &lt;/ChildClass.Child&gt;
        ///    &lt;/ChildClass&gt;
        ///  &lt;/DummyClass.Child&gt;
        ///&lt;/DummyClass&gt;.
        /// </summary>
        public static string ThreeLevelsOfNesting {
            get {
                return ResourceManager.GetString("ThreeLevelsOfNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;&gt;
        ///  &lt;DummyClass.Items&gt;
        ///    &lt;Item Title=&quot;Main1&quot; /&gt;
        ///    &lt;Item Title=&quot;Main2&quot; /&gt;
        ///  &lt;/DummyClass.Items&gt;
        ///  &lt;DummyClass.Child&gt;
        ///    &lt;ChildClass&gt;
        ///    &lt;/ChildClass&gt;
        ///  &lt;/DummyClass.Child&gt;
        ///&lt;/DummyClass&gt;.
        /// </summary>
        public static string TwoNestedProperties {
            get {
                return ResourceManager.GetString("TwoNestedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot;&gt;
        ///  &lt;DummyClass.Items&gt;   
        ///  &lt;/DummyClass.Items&gt;
        ///  &lt;DummyClass.Child&gt;    
        ///  &lt;/DummyClass.Child&gt;
        ///&lt;/DummyClass&gt;.
        /// </summary>
        public static string TwoNestedPropertiesEmpty {
            get {
                return ResourceManager.GetString("TwoNestedPropertiesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;ChildClass  xmlns=&quot;root&quot;&gt;
        ///  &lt;Item&gt;
        ///    &lt;Item Title=&quot;Item1&quot; /&gt;    
        ///  &lt;/Item&gt;
        ///  &lt;ChildClass.Child&gt;
        ///    &lt;ChildClass /&gt;
        ///  &lt;/ChildClass.Child&gt;
        ///&lt;/ChildClass&gt;.
        /// </summary>
        public static string TwoNestedPropertiesOneOfThemUsesContentPropertyWithSingleItem {
            get {
                return ResourceManager.GetString("TwoNestedPropertiesOneOfThemUsesContentPropertyWithSingleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;ChildClass  xmlns=&quot;root&quot;&gt;
        ///  &lt;Item&gt;
        ///    &lt;Item Title=&quot;Item1&quot; /&gt;    
        ///  &lt;/Item&gt;
        ///  &lt;ChildClass.Child&gt;
        ///    &lt;ChildClass /&gt;
        ///  &lt;/ChildClass.Child&gt;
        ///&lt;/ChildClass&gt;.
        /// </summary>
        public static string TwoNestedPropertiesOneOfThemUsesContentPropertyWithSingleItem1 {
            get {
                return ResourceManager.GetString("TwoNestedPropertiesOneOfThemUsesContentPropertyWithSingleItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;Unknown&gt;&lt;/Unknown&gt;.
        /// </summary>
        public static string UnknownType {
            get {
                return ResourceManager.GetString("UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DummyClass xmlns=&quot;root&quot; Container.Property=&quot;Value&quot;&gt;&lt;/DummyClass&gt;.
        /// </summary>
        public static string WithAttachableProperty {
            get {
                return ResourceManager.GetString("WithAttachableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;Window x:Class=&quot;WpfApplication_test1.MainWindow&quot;
        ///        xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///        xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot;
        ///        xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///        xmlns:local=&quot;clr-namespace:WpfApplication_test1&quot;
        ///        mc:Ignorable=&quot;d&quot;
        ///        Title=&quot;MainWindow&quot; Height=&quot;350&quot; Width=&quot;525&quot;&gt;
        ///  &lt;Grid Background=&quot;BlueViolet&quot;&gt;
        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string XamlStage1 {
            get {
                return ResourceManager.GetString("XamlStage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NamespaceDeclarationNamespaceDeclarationNamespaceDeclarationNamespaceDeclarationNamespaceDeclarationStartObjectStartMemberValueEndMemberStartMemberValueEndMemberStartMemberValueEndMemberStartMemberValueEndMemberStartMemberStartObjectStartMemberValueEndMemberStartMemberStartObjectStartMemberValueEndMemberEndObjectValueStartObjectStartMemberValueEndMemberEndObjectValueStartObjectStartMemberValueEndMemberEndObjectEndMemberStartMemberStartObjectStartMemberValueEndMemberStartMemberValueEndMemberStartMemberValueE [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string XamlStage1_Result {
            get {
                return ResourceManager.GetString("XamlStage1_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;UserControl
        ///    x:Class=&quot;NcoreCpuMarkW8.UI.Controls.UcSpeedmeter&quot;
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///    xmlns:local=&quot;using:NcoreCpuMarkW8.UI.Controls&quot;
        ///    xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot;
        ///    xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///    mc:Ignorable=&quot;d&quot;
        ///    d:DesignHeight=&quot;400&quot;
        ///    d:DesignWidth=&quot;600&quot;&gt;
        ///
        ///  &lt;Grid MinHeight=&quot;400&quot; MinWidth=&quot;600&quot;&gt;
        ///  [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string XamlStage2 {
            get {
                return ResourceManager.GetString("XamlStage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NamespaceDeclarationNamespaceDeclarationNamespaceDeclarationNamespaceDeclarationNamespaceDeclarationStartObjectStartMemberValueEndMemberStartMemberStartObjectStartMemberValueEndMemberStartMemberValueEndMemberStartMemberStartObjectStartMemberStartObjectStartMemberValueEndMemberEndObjectValueStartObjectStartMemberValueEndMemberStartMemberValueEndMemberStartMemberValueEndMemberStartMemberValueEndMemberStartMemberValueEndMemberStartMemberStartObjectStartMemberValueEndMemberStartMemberValueEndMemberEndObjectEndM [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string XamlStage2_Result {
            get {
                return ResourceManager.GetString("XamlStage2_Result", resourceCulture);
            }
        }
    }
}
